<a href="https://colab.research.google.com/github/21PA1A6156/numpypandas/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
x= np.array([1,2,3,4,45,2])
print(x)

[ 1  2  3  4 45  2]


In [3]:
y = np.array([[3,5,4,5],[45,4,5,5]])
print(y)

[[ 3  5  4  5]
 [45  4  5  5]]


In [6]:
a = np.append(x,[2,4,3])
print(a)

[ 1  2  3  4 45  2  2  4  3]


In [8]:
print ("before Deleting: ",a)
newarray = np.delete(a,2)
print(newarray)

before Deleting:  [ 1  2  3  4 45  2  2  4  3]
[ 1  2  4 45  2  2  4  3]


In [9]:
b = np.array([6,4,1,3,5,9])
b[b<4] = -1  
print(b)

[ 6  4 -1 -1  5  9]


In [10]:
b= np.array([123,4445])
print(b)

[ 123 4445]


In [31]:
a= np.array([0,20,30,40,50,69,70,89])
b= np.arange(8)
print("The elements in a are",a)
print("The elements in b are",b)
print("Result after Addition",a+b)
print("Result after substraction",a-b)
print("Result after multiplication",a*b)
print("Result after increasing the number to the power of 4",b**4) 
# Scalar multiplication(power)
print("Result after applying sin and multiplying with 10",10*np.sin(a))
a[0] +=10
b[0] +=10
print("Result after adding first element with 10",a)
print("Result after division",a/b)

The elements in a are [ 0 20 30 40 50 69 70 89]
The elements in b are [0 1 2 3 4 5 6 7]
Result after Addition [ 0 21 32 43 54 74 76 96]
Result after substraction [ 0 19 28 37 46 64 64 82]
Result after multiplication [  0  20  60 120 200 345 420 623]
Result after increasing the number to the power of 4 [   0    1   16   81  256  625 1296 2401]
Result after applying sin and multiplying with 10 [ 0.          9.12945251 -9.88031624  7.4511316  -2.62374854 -1.14784814
  7.73890682  8.60069406]
Result after adding first element with 10 [10 20 30 40 50 69 70 89]
Result after division [ 1.         20.         15.         13.33333333 12.5        13.8
 11.66666667 12.71428571]


In [32]:
print(np.dot(a,b))

1888


In [35]:
a =np.arange(10)**2
print(a)

[ 0  1  4  9 16 25 36 49 64 81]


In [43]:
# slicing and iterating of Numpy Arryas

print("The output of a[2] is", a[2])
print("The output of a[2] is", a[2:5])
print("The output of a[2] is", a[:2])
print("The output of a[2] is", a[-1])
print("The output of a[2] is", a[-5:-2])


The output of a[2] is 4
The output of a[2] is [ 4  9 16]
The output of a[2] is [0 1]
The output of a[2] is 81
The output of a[2] is [25 36 49]


In [47]:
a=np.arange(12).reshape(4,3)**2 
print("Let's consider an array\n",a)
print("\n")
for i in a:
        print(i*2)

Let's consider an array
 [[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]


[0 2 8]
[18 32 50]
[ 72  98 128]
[162 200 242]


In [48]:
a=np.floor(10*np.random.random((3,4))) # Create a rondom 3*4 matrix.
print("Let's consider a 1-D array\n",a)
print("After reshaping to 2 by 6 matrix\n",a.reshape(2,6))
print("To Flatten the array\n",a.ravel())
print("To transpose the array\n",a.T)

Let's consider a 1-D array
 [[5. 1. 7. 4.]
 [2. 2. 5. 1.]
 [8. 5. 5. 4.]]
After reshaping to 2 by 6 matrix
 [[5. 1. 7. 4. 2. 2.]
 [5. 1. 8. 5. 5. 4.]]
To Flatten the array
 [5. 1. 7. 4. 2. 2. 5. 1. 8. 5. 5. 4.]
To transpose the array
 [[5. 2. 8.]
 [1. 2. 5.]
 [7. 5. 5.]
 [4. 1. 4.]]
